# Generated by Django 2.2.6 on 2019-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0002_subjectarea_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectarea',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
