# Generated by Django 2.2.6 on 2019-10-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0003_auto_20191013_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.CharField(choices=[('instructional_designer', 'Instructional Designer'), ('curriculum', 'Curriculum Alignment Expert'), ('content_expert', 'OER Expert'), ('teacher', 'Teacher/Coach'), ('designer', 'Designer or Frontend Developer'), ('developer', 'Technologist and/or Developer'), ('data_science', 'Machine Learning and Data Science'), ('metadata', 'Metadata'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject_areas',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='alignmentapp.SubjectArea'),
        ),
    ]
