##################################################
# MIT License
#
# Copyright (c) 2019 Learning Equality
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
##################################################

# Generated by Django 2.2.6 on 2019-10-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0003_auto_20191013_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.CharField(choices=[('instructional_designer', 'Instructional Designer'), ('curriculum', 'Curriculum Alignment Expert'), ('content_expert', 'OER Expert'), ('teacher', 'Teacher/Coach'), ('designer', 'Designer or Frontend Developer'), ('developer', 'Technologist and/or Developer'), ('data_science', 'Machine Learning and Data Science'), ('metadata', 'Metadata'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject_areas',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='alignmentapp.SubjectArea'),
        ),
    ]
