# Generated by Django 2.2.6 on 2019-10-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0005_auto_20191023_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsection',
            name='output_dir',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='documentsection',
            name='num_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentsection',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
