# Generated by Django 2.2.6 on 2019-10-28 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alignmentapp', '0006_auto_20191023_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsection',
            name='output_dir',
        ),
        migrations.AddField(
            model_name='documentsection',
            name='reviewed_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
