# Generated by Django 2.2.6 on 2019-10-30 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0009_auto_20191029_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsection',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
