# Generated by Django 2.2.6 on 2019-10-30 16:57

import alignmentapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0010_auto_20191030_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsection',
            name='section_zip',
            field=models.FileField(blank=True, null=True, upload_to=alignmentapp.models.overwriting_file_upload_name),
        ),
    ]
