# Generated by Django 2.2.6 on 2019-10-30 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0011_auto_20191030_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
