# Generated by Django 2.2.6 on 2019-10-30 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alignmentapp', '0012_auto_20191030_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActions',
            new_name='UserAction',
        ),
    ]
