# Generated by Django 2.2.6 on 2019-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0013_auto_20191030_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdocument',
            name='official',
            field=models.BooleanField(default=False, help_text='Curriculum document is an official national standard'),
        ),
    ]
