# Generated by Django 2.2.7 on 2019-11-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignmentapp', '0014_curriculumdocument_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
